@startuml library
scale 1

entity "Читатели" as readers {
  + Номер читательского билета [PK]
  --
  ФИО
  Адрес
  Телефон
  --
  Шифр книги [FK]
}

entity "Книги" as books {
  + Шифр книги [PK]
  --
  Название [FK]
  Автор(ы)
  Год издания
  Объем (в страницах)
  Цена
  Количество экземпляров в фонде 
}

entity "Издательства" as publishers {
  + Название [PK]
  --
  Город
}

readers ||--o{ books : Шифр книги
books }o--|| publishers : Название

@enduml