@startuml library
scale 1

entity "Читатели" as readers {
  + Номер читательского билета [PK]
  --
  ФИО
  Адрес
  Телефон
}

entity "Книги" as books {
  + Шифр книги [PK]
  --
  Название
  Автор(ы)
  Год издания
  Объем (в страницах)
  Цена
  Количество экземпляров в фонде
  --
  Номер читательского билета [FK]
  Идентификатор издательства [FK]
}

entity "Издательства" as publishers {
  + Идентификатор издательства [PK]
  --
  Название
  Город
}

readers ||--o{ books : Номер читательского билета
books }o--|| publishers : Идентификатор издательства

@enduml