@startuml library
scale 1

entity "Читатели" as readers {
  + Номер читательского билета [PK]
  --
  ФИО
  Адрес
  Телефон
}

entity "Книги" as books {
  + Шифр книги [PK]
  --
  Название
  Автор(ы)
  Год издания
  Объем (в страницах)
  Цена
  Количество экземпляров в фонде
  --
  Идентификатор издательства [FK]
}

entity "Издательства" as publishers {
  + Идентификатор издательства [PK]
  --
  Название
  Город
}

entity "Автор" as author {
  + Идентификатор автора [PK]
  --
  ФИО автора 
}

entity "Выдача_Книги" as issuing {
  --
  Номер читательского билета [FK]
  Шифр книги [FK]
}

entity "Автор_Книги" as book_author {
  --
  Идентификатор автора [FK]
  Шифр книги [FK]
}

books }o--|| publishers : Идентификатор издательства
issuing }o--|| books : Шифр книги
issuing }o--|| readers : Номер читательского билета
book_author }o--|| author : Идентификатор автора
book_author }o--|| books : Шифр книги

@enduml